spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_account
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
#这个日志实际上是用的MyBatis里边的日志信息，使用mybatis-plus表示配置configuration的log-impl指定日志的实现类(输出到控制台上的)
#配置方式可以参考MyBatis的官方文档查看日志的实现（StdOutImpl这是其中的一个在控制台打印日志）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

